"""
Renders a .voa area project file using the values that produced the
known-good sample itshfbc/areadata/default/default.voa (shipped in
jawatson/voacapl's own repo, not generated by us), then byte-diffs the
result against that real file.

This replaces an earlier version of this test that byte-diffed against
itshfbc/run/voaareax.da1 using a fixed-column CIRCUIT/AREA card deck -
that format turned out to be a red herring: voaareax.da1 is an
intermediate file voacapl itself generates from a .voa file, not something
we're meant to author directly. See area_deck.py's module docstring for
how this was actually confirmed (running the real default.voa sample
through voacapl on a live cluster).

Antenna reference lines are expected to differ (this sample uses
voacapl's own default/const17.voa + default/swwhip.voa; our app's catalog
lives under samples/) - every other line must match exactly.
Run directly: python test_area_deck_roundtrip.py
"""
import sys
from pathlib import Path

from area_deck import AreaRequest, render_area_voa
from deck import Antenna

SAMPLE_PATH = Path("/mnt/c/Users/chris/Desktop/CLAUDE/VOCAP FILES/itshfbc/areadata/default/default.voa")

req = AreaRequest(
    label="TANGIER, Morocco",
    center_lat=35.80,
    center_lon=-5.90,
    radius_km=6000.0,  # box is -1000/+6000 east-west (asymmetric - see below)
    grid_points=242,
    hour_gmt=18,
    month=6,
    year=2026,  # not present in a .voa file (see area_deck.py - no Year field)
    sunspot_number=100.0,
    tx_antenna=Antenna(sample_file="SAMPLE.23", bearing_deg=57.0, power_kw=500.0),
    rx_antenna=Antenna(sample_file="SAMPLE.00", bearing_deg=0.0, power_kw=0.0),
    frequency_mhz=11.85,
    min_takeoff_angle_deg=0.10,
    required_snr_db=73.0,
)

rendered_lines = [line.rstrip() for line in render_area_voa(req).splitlines()]
original_lines = [
    line.rstrip() for line in SAMPLE_PATH.read_text(encoding="ascii", newline="").splitlines()
]

mismatches = []
for i, (r, o) in enumerate(zip(rendered_lines, original_lines)):
    if r == o:
        continue
    if r.startswith(("Rec Ants", "Tx Ants")) and o.startswith(("Rec Ants", "Tx Ants")):
        continue
    if r.startswith("Area") and o.startswith("Area"):
        # v1 only supports a symmetric radius; the fixture's box is
        # asymmetric (-1000/+6000 east-west, -1000/+4000 south-north) - all
        # four extent values legitimately differ from a symmetric render.
        # Only the "Area     :" label prefix is checked here.
        if r[:10] == o[:10]:
            continue
    mismatches.append((i + 1, r, o))

if not mismatches and len(rendered_lines) == len(original_lines):
    print("MATCH (except expected antenna and asymmetric-radius differences)")
    sys.exit(0)

for line_no, r, o in mismatches:
    print(f"line {line_no}:")
    print(f"  rendered: {r!r}")
    print(f"  original: {o!r}")
if len(rendered_lines) != len(original_lines):
    print(f"line count differs: rendered={len(rendered_lines)} original={len(original_lines)}")
sys.exit(1)
